### PR TITLE
#33 Add 'OldestCommitToProcess' setting

### PR DESCRIPTION
**Pull request by mmaruniak**
This will allow to limit the history to generate release notes from to a specified commit.

### CODE REVIEW

**Comment by rnowosielski** [comment]
I'm looking at it :) But it seems the code coverage fell :D

**Comment by rnowosielski** [comment]
I pulled this version locally and I am trying to build my release notes. I am getting an error: 

```
No artifacter configured: every version tag will be considered a valid release
Git: Cloning <address> at /Users/rnowosielski/Documents/workspace/ivbcore/.
Git: Retrieving Git history...
Git: Retrieving versions (git tags)...
Make sure you first retrieve the promoted version: Promoted versions are empty, thus every tag matching will be considered as released

Generating using StashMarkdownWriter
Generating info for version 1.0.0
Traceback (most recent call last):
  File "/usr/local/bin/just_release", line 9, in <module>
    load_entry_point('JustReleaseNotes==0.1.8', 'console_scripts', 'just_release')()
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/command_line.py", line 26, in main
    generate_release_notes(args.config)
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/command_line.py", line 92, in generate_release_notes
    generateForOneWriter(generator, ticketProvider, writerConf["Provider"], os.path.dirname(path), os.path.basename(path))
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/command_line.py", line 44, in generateForOneWriter
    releaseNotes = generator.generateReleaseNotesByPromotedVersions(writer)
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/releaseNotes.py", line 56, in generateReleaseNotesByPromotedVersions
    if self.__repo.gitDatesByHash[hash] < self.__fromDate:
KeyError: u'e58ca29c5405f0a5fde04f63fab60218ad63f62d'
rake aborted!
Error while generating release notes with JustReleaseNotes
/Users/rnowosielski/Documents/workspace/ivbcore/Rakefile:152:in `block in <top (required)>'
Tasks: TOP => release_notes
(See full trace by running task with --trace)
rafalsnwmacbook:ivbcore rnowosielski$ 
```

**Comment by rnowosielski** [comment]
I think the line you added might not be covered in unit tests.

**Comment by mmaruniak** [comment]
It looks like the exception you're getting is due to a missing entry in self.__repo.gitDatesByHash for commit 'e58ca29c5405f0a5fde04f63fab60218ad63f62d' . Is it the same case when you generate notes from a remote repository?

**Comment by mmaruniak** [comment]
As for the coverage, I added a test case to cover all the lines I added, but the report still keeps failing.

**Comment by rnowosielski** [comment]
What do you mean by "when you generate notes from a remote repository" ? 

My config file looks like this:

```
{
  "pathToSave" : ".",

    "packages" : {
        "ivbcore" : {
            "Issues" : [{
                 "Provider" : "JiraIssues",
                 "HtmlUrl" : "https://<other_jira_url>/browse",
                 "Authorization" : "Basic ENV[authDwd]",
                 "Url" : "https://<other_jira_url>/rest/api/2/issue",
                 "TicketRegex" : "(?:LAB|IC|IA|PRIN)-[0-9]+"
            },
            {
                 "Provider" : "JiraIssues",
                 "HtmlUrl" : "https://<jira_url>/browse",
                 "Authorization" : "Basic ENV[authJiraTrain]",
                 "Url" : "https://<jira_url>/rest/api/2/issue",
                 "TicketRegex" : "(?:MB)-[0-9]+"
            }],
            "Source" : {
                 "Provider" : "GitRepo",
                 "Directory" : ".",
                 "Branch" : "ENV[GIT_BRANCH]",
                 "RepositoryUrl" : "https://<stash_url>/scm/mib/ivbcore.git",
                 "VersionTagRegex" : "^([0-9]+\\.[0-9]+\\.[0-9]+)$"
            },
            "ReleaseNotesWriter" : [
              {
                "Provider" : "StashMarkdownWriter",
                "PathToSave" : "index.md"
              },
              {
                "Provider" : "HtmlWriter",
                "PathToSave" : "wwwroot/release_notes.html"
              }
            ]
        }
    }
}
```

and then I just do `just_release notes`

**Comment by rnowosielski** [comment]
And that works in whatever is currently released - I didn't look deep into the code as to why it might have stopped working: I can debug it when I get time but I guess ti will be Friday :)

**Comment by istanishev** [comment]
Looks ok. @rnowosielski you should not see the error anymore, could you please check?

**Comment by rnowosielski** [comment]
It still doesn't work for me - this time I have a different issues :)

It start like..

```
o artifacter configured: every version tag will be considered a valid release
Git: Cloning https://mcpstash.cimpress.net/scm/mib/ivbcore.git at /Users/rnowosielski/Documents/workspace/ivbcore/.
Git: Retrieving Git history...
Traceback (most recent call last):
  File "/usr/local/bin/just_release", line 9, in <module>
    load_entry_point('JustReleaseNotes==0.1.8', 'console_scripts', 'just_release')()
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/command_line.py", line 26, in main
    generate_release_notes(args.config)
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/command_line.py", line 85, in generate_release_notes
    generator = ReleaseNotes(conf, ticketProvider, repo, promotedVersionsInfo)
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/releaseNotes.py", line 19, in __init__
    self.__repo.retrieveHistory()
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/sourcers/GitRepo.py", line 111, in retrieveHistory
    self.__processCommit(i)
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/sourcers/GitRepo.py", line 106, in __processCommit
```

and then it continues like this for few screens...
to finish like this:

```
File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/sourcers/GitRepo.py", line 106, in __processCommit
    self.setParents(commit)
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/sourcers/GitRepo.py", line 81, in setParents
    self.__processCommit(p)
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/sourcers/GitRepo.py", line 103, in __processCommit
    self.gitCommitMessagesByHash[commit.hexsha] = commit.summary + commit.message
  File "/Library/Python/2.7/site-packages/git/objects/commit.py", line 146, in summary
    return self.message.split('\n', 1)[0]
  File "/Library/Python/2.7/site-packages/gitdb/util.py", line 237, in __getattr__
    self._set_cache_(attr)
  File "/Library/Python/2.7/site-packages/git/objects/commit.py", line 137, in _set_cache_
    binsha, typename, self.size, stream = self.repo.odb.stream(self.binsha)
  File "/Library/Python/2.7/site-packages/gitdb/db/base.py", line 208, in stream
    return self._db_query(sha).stream(sha)
  File "/Library/Python/2.7/site-packages/gitdb/db/pack.py", line 104, in stream
    return entity.stream_at_index(index)
  File "/Library/Python/2.7/site-packages/gitdb/pack.py", line 778, in stream_at_index
    return self._object(None, True, index)
  File "/Library/Python/2.7/site-packages/gitdb/pack.py", line 724, in _object
    packstream = self._pack.stream(offset)
  File "/Library/Python/2.7/site-packages/gitdb/pack.py", line 636, in stream
    return pack_object_at(self._cursor, offset or self.first_object_offset, True)[1]
  File "/Library/Python/2.7/site-packages/gitdb/pack.py", line 124, in pack_object_at
    return abs_data_offset, OPackStream(offset, type_id, uncomp_size, stream)
  File "/Library/Python/2.7/site-packages/gitdb/base.py", line 80, in __init__
    tuple.__init__(self)
RuntimeError: maximum recursion depth exceeded while calling a Python object
rake aborted!
Error while generating release notes with JustReleaseNotes
/Users/rnowosielski/Documents/workspace/ivbcore/Rakefile:152:in `block in <top (required)>'
Tasks: TOP => release_notes
(See full trace by running task with --trace)
rafalsnwmacbook:ivbcore rnowosielski$ 
```

Sorry that my feedback is just running JustReleaseNotes and pasting output, but I am slightly overloaded right now. Didn't have time to see in the code what is happening - but my guess is that there is some indefinite recursion :? I will be flying tomorrow, so we can have a look at it on Friday together.

**Comment by istanishev** [comment]
Thanks Rafal, I'll try to test with your repo. It will be interesting to see why we don't see this for our repos.

**Comment by mmaruniak** [comment]
My suspicion would be number of commits in your repo which cause some recursive function to overflow. The previous issue was also related to it (commits after the 1024 limit were retrieved slightly differently).

**Comment by istanishev** [comment]
Could you please squash the latest 3 commits (the ones for #47) together.

**Comment by mmaruniak** [comment]
@istanishev good idea, it's done

**Pull request merged**
