### PR TITLE
Simplify EnvReplacer

### PR DESCRIPTION
**Pull request by jlaire**

### CODE REVIEW

**Comment by rnowosielski** [comment]
You broke Unit Tests ? :)

**Comment by jlaire** [comment]
They pass on my machine! We should run them in verbose mode, now there's no output on Travis.

Locally I do `python -m unittest discover -v -p '*_Test.py'` instead of `python unit_tests.py`, I'll try to modify unit_tests.py to print stuff.

**Comment by rnowosielski** [comment]
I ran the tests on this PR on my machine. The error is:

```
======================================================================
ERROR: test_stringWithMixedCaseEnvKeyIsReplaced (tests.utils.EnvReplacer_Test.EnvParser_Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/tests/utils/EnvReplacer_Test.py", line 49, in test_stringWithMixedCaseEnvKeyIsReplaced
    self.assertEqual("1 1 1", EnvReplacer.replace(conf))
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/utils/EnvReplacer.py", line 10, in replace
    return __replaceStr(config)
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/utils/EnvReplacer.py", line 27, in __replaceStr
    return re.sub(r'ENV\[(\w+)\]', __findEnvKey, str, flags=re.IGNORECASE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/Users/rnowosielski/Documents/workspace/JustReleaseNotes/JustReleaseNotes/utils/EnvReplacer.py", line 31, in __findEnvKey
    return os.environ[match.group(1)]
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'FOO'
```

**Comment by rnowosielski** [comment]
I guess it has something to do with the fact that the tests assume that `ENV["FOO"]` will work when the only available environment variable if `foo`

**Comment by istanishev** [comment]
What would be the "expected" behavior? Do we want the generation to fail saying "Environment variable X is not found" or we should do what Jenkins for example is doing - do not replace and consider it as normal text. (Edit: and maybe fail later...)

**Comment by rnowosielski** [comment]
I guess environment variables (at least in some systems) are case sensitive. So `$path` and `$Path` could be 2 different variables with different meaning.

I lean towards either failing generation, or assuming empty value. With higher preference towards failing generation.

**Comment by istanishev** [comment]
I'm ok with failing if the env doesn't exists.

On windows, the env params are NOT case sensitive:
C:\vp\legacyplant>set Abc=123
C:\vp\legacyplant>set abc=456
C:\vp\legacyplant>echo %Abc%
456

I guess, to support both, we can check if exact match exists, if no, check for case-insensitve match, if no, fail. What do you think?

**Comment by rnowosielski** [comment]
That sounds ok. But I guess @jlaire has to do it because I don't have access to his fork (to fix this pull request).

**Comment by jlaire** [comment]
Ah, the test passes on my machine (on Windows). It depends on the OS's behavior, the code uses the string between [] as-is to get the value from `os.environ[]`.

I'll remove that test.

**Comment by istanishev** [comment]
Wouldn't it be better to change the implementation instead of removing the test?

**Comment by jlaire** [comment]
The test was testing that `env[Foo]` and `env[foo]` are the same thing. I don't think we should worry about that.

**Comment by istanishev** [comment]
:+1:

**Pull request merged**
